- hosts: fmg-dev-001
  collections:
  - fortinet.fortimanager
  vars:
    adom_name: new_adom_name
    device_group_name: FGT
    device_name: fwl-dev-001
  tasks:
  - name: Add firewall to Device Group
    fmgr_dvmdb_group_objectmember:
      bypass_validation: False
      adom: "{{adom_name}}"
      group: "{{device_group_name}}"
      state: "present"
      proposed_method: "add"
      dvmdb_group_objectmember:
        name: "{{device_name}}"
        vdom: "root"