- hosts: fmg-dev-001
  collections:
  - fortinet.fortimanager
  vars:
    adom_name: new_adom_name
    policypackage_name: testpackage
    device_name: fwl-dev-001
  tasks:
  - name: Assign Policy Package
    fmgr_pm_pkg_scopemember:
      bypass_validation: False
      adom: "{{adom_name}}"
      pkg_path: "{{policypackage_name}}"
      state: present
      proposed_method: "add"
      pm_pkg_scopemember:
        name: "{{device_name}}"
        vdom: root